Repository buildfarm/buildfarm, pull requests merged in 2024-12, with the labels that each got.

#2055 refactor: prefer Path.of() instead of Paths.get()
  persistentworkers/src/main/java/persistent/common/util/Args.java
  persistentworkers/src/test/java/persistent/testutil/ProcessUtils.java
  src/main/java/build/buildfarm/common/config/BuildfarmConfigs.java
  src/main/java/build/buildfarm/common/config/Worker.java
  src/main/java/build/buildfarm/tools/Cat.java
  src/main/java/build/buildfarm/tools/Executor.java
  src/main/java/build/buildfarm/tools/Extract.java
  src/main/java/build/buildfarm/tools/Mount.java
  src/main/java/build/buildfarm/tools/Upload.java
  src/main/java/build/buildfarm/tools/WorkerProfile.java
  src/main/java/build/buildfarm/worker/DockerExecutor.java
  src/main/java/build/buildfarm/worker/cgroup/Group.java
  src/main/java/build/buildfarm/worker/persistent/PersistentExecutor.java
  src/main/java/build/buildfarm/worker/persistent/ProtoCoordinator.java
  src/test/java/build/buildfarm/cas/cfc/HexBucketEntryPathStrategyTest.java
  src/test/java/build/buildfarm/common/CommandUtilsTest.java
  src/test/java/build/buildfarm/examples/ExampleConfigsTest.java
  src/test/java/build/buildfarm/worker/ExecuteActionStageTest.java
  src/test/java/build/buildfarm/worker/InputFetcherTest.java
  src/test/java/build/buildfarm/worker/ReportResultStageTest.java
  src/test/java/build/buildfarm/worker/util/InputsIndexerTest.java
  src/test/java/build/buildfarm/worker/util/WorkerTestUtils.java
Labels: refactor

#2069 doc(site): update link to Queues
  _site/docs/execution/execution_properties.md
Labels: Documentation

#2080 feat(persistent): add allowlist for persistent worker actions
  _site/docs/configuration/configuration.md
  examples/config.yml
  src/main/java/build/buildfarm/common/config/Worker.java
  src/main/java/build/buildfarm/worker/Executor.java
Labels: enhancement

#2084 Unique Execution Owners
  _site/docs/configuration/configuration.md
  as-nobody.c
  src/main/java/build/buildfarm/common/Claim.java
  src/main/java/build/buildfarm/common/config/LimitedResource.java
  src/main/java/build/buildfarm/common/config/Worker.java
  src/main/java/build/buildfarm/worker/CFCExecFileSystem.java
  src/main/java/build/buildfarm/worker/CFCLinkExecFileSystem.java
  src/main/java/build/buildfarm/worker/DequeueMatchEvaluator.java
  src/main/java/build/buildfarm/worker/ExecFileSystem.java
  src/main/java/build/buildfarm/worker/ExecutionContext.java
  src/main/java/build/buildfarm/worker/Executor.java
  src/main/java/build/buildfarm/worker/InputFetcher.java
  src/main/java/build/buildfarm/worker/MatchListener.java
  src/main/java/build/buildfarm/worker/MatchStage.java
  src/main/java/build/buildfarm/worker/ResultReporter.java
  src/main/java/build/buildfarm/worker/WorkerContext.java
  src/main/java/build/buildfarm/worker/resources/LocalResourceSet.java
  src/main/java/build/buildfarm/worker/resources/LocalResourceSetUtils.java
  src/main/java/build/buildfarm/worker/shard/FuseExecFileSystem.java
  src/main/java/build/buildfarm/worker/shard/ShardWorkerContext.java
  src/main/java/build/buildfarm/worker/shard/Worker.java
  src/test/java/build/buildfarm/worker/DequeueMatchEvaluatorTest.java
  src/test/java/build/buildfarm/worker/InputFetcherTest.java
  src/test/java/build/buildfarm/worker/ReportResultStageTest.java
  src/test/java/build/buildfarm/worker/StubWorkerContext.java
  src/test/java/build/buildfarm/worker/resources/LocalResourceSetUtilsTest.java
  src/test/java/build/buildfarm/worker/shard/ShardWorkerContextTest.java
Labels: enhancement
