Repository buildfarm/buildfarm, pull requests merged in 2024-10, with the labels that each got.

#1851 chore(deps): bump bazel_skylib
  MODULE.bazel
Labels: dependencies

#1852 chore(deps): bump platforms
  MODULE.bazel
Labels: dependencies

#1880 Pipelined BackplaneStatus
  src/main/java/build/buildfarm/common/Queue.java
  src/main/java/build/buildfarm/common/redis/BalancedRedisQueue.java
  src/main/java/build/buildfarm/common/redis/RedisClient.java
  src/main/java/build/buildfarm/common/redis/RedisHashMap.java
  src/main/java/build/buildfarm/common/redis/RedisPriorityQueue.java
  src/main/java/build/buildfarm/common/redis/RedisQueue.java
  src/main/java/build/buildfarm/instance/shard/ExecutionQueue.java
  src/main/java/build/buildfarm/instance/shard/RedisShardBackplane.java
  src/test/java/build/buildfarm/worker/cgroup/GroupTest.java
Labels: Performance

#1886 chore(deps): bumping .bazelversion
  .bazelversion
Labels: dependencies

#1885 Bump remoteapis version
  MODULE.bazel
  maven_install.json
  persistentworkers/src/main/java/persistent/bazel/processes/ProtoWorkerRW.java
  src/main/java/build/buildfarm/common/grpc/Retrier.java
  src/main/java/build/buildfarm/instance/shard/Util.java
  src/main/java/build/buildfarm/instance/stub/StubInstance.java
  src/test/java/build/buildfarm/common/grpc/ByteStreamServiceWriter.java
  src/test/java/build/buildfarm/common/grpc/StubWriteOutputStreamTest.java
Labels: dependencies

#1946 Feature: multi-platform (x86_64 and Arm64) images
  .bazelrc
  .github/workflows/buildfarm-release-build-and-deploy.yml
  BUILD
  MODULE.bazel
  container/BUILD
  container/defs.bzl
  container/test/BUILD
  extensions.bzl
  third_party/BUILD.skip_sleep
Labels: enhancement
